[package]
name = "iroha2_explorer_web"
version = "0.2.0"
edition = "2021"

[dependencies]
iroha_data_model = { git = "https://github.com/DCNick3/iroha.git", branch = "simplify-query-filters" }
iroha_telemetry = { git = "https://github.com/DCNick3/iroha.git", branch = "simplify-query-filters" }
iroha_crypto = { git = "https://github.com/DCNick3/iroha.git", branch = "simplify-query-filters" }
iroha_config = { git = "https://github.com/DCNick3/iroha.git", branch = "simplify-query-filters" }

tracing = "0.1.32"
tracing-subscriber = { version = "0.3.10", features = ["env-filter"] }
color-eyre = "0.5"
serde = "1.0"
serde_json = "1.0"
clap = { version = "4", features = ["derive", "env"] }
futures = "0.3.30"
http = "0.2.6"
chrono = { version = "0.4.19", features = ["serde"] }
hex = "0.4.3"
parity-scale-codec = "3.2.1"
thiserror = "1.0"
url = "2.4.0"
axum = { version = "0.7.5", features = ["http2", "macros"] }
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
reqwest = "0.12.5"
tower-http = { version = "0.5.2", features = ["trace"] }
utoipa = { version = "4.2.3", features = ["axum_extras"] }
utoipa-scalar = { version = "0.1.0", features = ["axum"] }
