[package]
name = "iroha_explorer"
version = "0.2.0"
edition = "2021"

[dependencies]
iroha_data_model = { git = "https://github.com/hyperledger/iroha.git", rev = "7473d0453d752311317f29f9dda20eff22d99bb1" }
iroha_telemetry = { git = "https://github.com/hyperledger/iroha.git", rev = "7473d0453d752311317f29f9dda20eff22d99bb1" }
iroha_crypto = { git = "https://github.com/hyperledger/iroha.git", rev = "7473d0453d752311317f29f9dda20eff22d99bb1" }

tracing = "0.1.32"
tracing-subscriber = { version = "0.3.10", features = ["env-filter"] }
color-eyre = "0.5"
serde = "1.0"
serde_json = "1.0"
clap = { version = "4", features = ["derive", "env"] }
futures = "0.3.30"
http = "0.2.6"
chrono = { version = "0.4.19", features = ["serde"] }
hex = "0.4.3"
parity-scale-codec = "3.2.1"
thiserror = "1.0"
url = "2.4.0"
axum = { version = "0.7.5", features = ["http2", "macros"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.12.5"
tower-http = { version = "0.5.2", features = ["trace"] }
utoipa = { version = "4.2.3", features = ["axum_extras"] }
utoipa-scalar = { version = "0.1.0", features = ["axum"] }
nonzero_ext = "0.3.0"
serde_with = "3.9.0"
sqlx = { version = "0.8.0", features = ["sqlite", "runtime-tokio", "chrono"] }
eyre = "0.6.12"

[dev-dependencies]
expect-test = "1.5.0"
