name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  fmt_clippy_tests:
    runs-on: ubuntu-latest

    steps:
    # v4.1.1
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

    # v2.7.3
    - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
      with:
        cache-provider: "buildjet"

    # v2.44.30
    - name: Install clippy-sarif
      uses: taiki-e/install-action@f06446b5f0cca77ab90b7b2ad3b01677f1d09ee9
      with:
        tool: clippy-sarif, sarif-fmt

    - name: Check code formatting
      run: cargo fmt -- --check || echo "fmt_failed=true" >> $GITHUB_ENV

    - name: Run Clippy (Lints for tests)
      run: cargo clippy --tests --message-format=json -- -D warnings | clippy-sarif | tee results.sarif | sarif-fmt || echo "clippy_failed=true" >> $GITHUB_ENV

    - name: Run Tests
      run: cargo test || echo "test_failed=true" >> $GITHUB_ENV

    # v3.26.11
    - name: Upload SARIF file
      if: always()
      uses: github/codeql-action/upload-sarif@cf5b0a9041d3c1d336516f1944c96d96598193cc
      with:
        sarif_file: results.sarif
        wait-for-processing: true

    - name: Final status check
      if: always()
      run: |
        if [[ "$fmt_failed" == "true" || "$clippy_failed" == "true" || "$test_failed" == "true" ]]; then
          echo "One or more checks failed."
          exit 1
        fi